spring:
  application:
    name: movie
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mysql
    username: root
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: varchar
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
